server:
  port: 7661

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sadeepMihiranga/hy-config-server
          clone-on-start: true